#!perl
use strict;
use warnings;
use lib 'lib';
use Dainamo::Runner;

my $runner = Dainamo::Runner->new;
$runner->parse_option(@ARGV);
$runner->run;

__END__

=head1 NAME dainamo

daimano - manage woker processes

=head1 SYNOPSIS
